api/urls.py
from django.urls import path
from .views import (
    APIListCreateCategory,
    APIUpdateDeleteRetriveCategory,
    APIListCategoryInfo,
    APIDestoryCategoryInfo,
    BudgetSummary,
)

urlpatterns = [
    path("", APIListCreateCategory.as_view()),
    path("<int:pk>/category/", APIUpdateDeleteRetriveCategory.as_view()),
    path("<int:pk>/delete_catinfo/", APIDestoryCategoryInfo.as_view()),
    path("list_category/", APIListCategoryInfo.as_view()),
    path("get_summary/", BudgetSummary.as_view()),
]

budget/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# import rest_auth.serializers
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("category.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("v1/api/", include("api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("rest-auth/", include("rest_auth.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/urls.py
from django.urls import path
from .views import (
    CatInfoListView,
    CatInfoDeleteView,
    CatViewInfo,
    CatListView,
    CatCreateView,
    CatUpdateView,
    CatDeleteView,
    CatInfoAddView,
)

urlpatterns = [
    path("", CatInfoListView.as_view(), name="home"),
    path("info/add/", CatInfoAddView.as_view(), name="cat_info_add"),
    path("info/<int:pk>/delete/", CatInfoDeleteView.as_view(), name="cat_info_delete"),
    path("category_add/", CatCreateView.as_view(), name="cat_add"),
    path("settings/category", CatListView.as_view(), name="cat_list"),
    path("<int:pk>/category_info/", CatViewInfo.as_view(), name="info"),
    path("<int:pk>/category_update/", CatUpdateView.as_view(), name="cat_update"),
    path("<int:pk>/category_delete/", CatDeleteView.as_view(), name="cat_delete"),
]

category/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model


class category(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    budget = models.FloatField(default=0)
    amt_left = models.FloatField(default=0)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse_lazy("home")


class category_info(models.Model):
    cat = models.ForeignKey(category, on_delete=models.CASCADE)
    spend = models.FloatField()
    item = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.cat}_info {self.date.ctime()}"

    def get_absolute_url(self):
        return reverse_lazy("home")

category/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    UpdateView,
    DetailView,
)
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .form import CatCreateForm, CatInfoForm
from .models import category, category_info
from .services import amt_remaining, get_budget_summary


class CatListView(LoginRequiredMixin, ListView):
    model = category
    template_name = "category_list.html"

    def get_queryset(self):
        return category.objects.filter(user=self.request.user)


class CatCreateView(LoginRequiredMixin, CreateView):
    model = category
    template_name = "category_add.html"
    form_class = CatCreateForm

    def form_valid(self, form):
        budget = form.cleaned_data["budget"]
        form.instance.amt_left = budget
        form.instance.user = self.request.user
        return super().form_valid(form)


class CatUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = category
    template_name = "category_update.html"
    form_class = CatCreateForm

    def form_valid(self, form):
        budget = form.cleaned_data["budget"]
        form.instance.amt_left = amt_remaining(form.instance.user, budget)
        form.instance.user = self.request.user
        form.instance.budget = budget
        return super().form_valid(form)

    def test_func(self):
        return self.get_object().user == self.request.user


class CatDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = category
    template_name = "category_delete.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        return self.get_object().user == self.request.user


class CatViewInfo(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = category
    template_name = "category_detail.html"

    def test_func(self):
        return self.get_object().user == self.request.user


class CatInfoListView(ListView):
    template_name = "category_info_list.html"

    def get_queryset(self):
        return category_info.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        budget_summary = get_budget_summary(user=self.request.user)

        return super().get_context_data(**kwargs) | budget_summary

    def get(self, request, *args, **kwargs):
        print(request.user.is_authenticated)
        if request.user.is_authenticated:
            return super().get(request, *args, **kwargs)
        return render(request, "home.html")


# to add the spendings
class CatInfoAddView(LoginRequiredMixin, CreateView):
    model = category_info
    form_class = CatInfoForm
    template_name = "category_info_add_update.html"

    def form_valid(self, form):
        form.instance.item = form.instance.item.title()
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


# delete view
class CatInfoDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = category_info
    template_name = "category_delete.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        return self.get_object().user == self.request.user

category/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">

    <!-- fa icons -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- social media icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

    <link rel="stylesheet" href="{% static 'css/regis.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    {% block additional %}
    {% endblock additional %}

    {% block meta %}
    {% endblock meta %}

    <title>{%block title%}Home{% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
        <a href="{% url 'home' %}" class="navbar-brand"><i class="fa fa-dollar"></i>Budget<b>Helper</b></a>
        {% if user.is_authenticated %}
        <button type="button" class="navbar-toggler col-2" data-toggle="collapse" data-target="#navbarCollapse"
            style="padding: 0;">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">

            <div class="navbar-nav ml-auto">
                <a href="{% url 'home' %}" class="nav-item nav-link">
                    <i class="fa fa-home"></i><span style="text-align: center;">Home</span></a>
                <a href="{% url 'cat_list' %}" class="nav-item nav-link"><i
                        class="fa fa-pie-chart"></i><span>Analytics</span></a>
                <div class="nav-item dropdown col-6">
                    <a href="#" data-toggle="dropdown" class="nav-item nav-link dropdown-toggle user-action"><img
                            sizes="21,12" src="{{ user.profile_pic.url }}" class="avatar" alt="Avatar">
                        {{user.username}} <b class="caret"></b></a>
                    <div class="dropdown-menu" style="left:-20px">
                        <a href="{% url 'edit_profile' user.pk %}" class="dropdown-item"><i class="fa fa-user"></i>
                            Profile</a>
                        <a href="#" class="dropdown-item" onclick="cat_add()"><i class="fa fa-plus"></i> Add
                            Category</a>
                        <div class="divider dropdown-divider"></div>
                        <a href="{% url 'logout' %}" class="dropdown-item"><i class=" fa fa-power-off"
                                style="font-size: large;"></i>
                            Logout</a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <!-- <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start"> -->

        <div class="ml-auto" style="display: inline-block;">
            <a href="{% url 'signup' %}"><button class="btn" id="signup"
                    style="border: 1px solid black;">Signup</button></a>
            <a href="{% url 'login' %}"><button class="btn btn-primary">Login</button></a>
        </div>
        <!-- </div> -->
        {%endif%}
    </nav>
    <div id="content">

        {% block content%}
        {% endblock content %}
    </div>
    <footer id="footer" class="mt- ">
        <div class="ml-1 mb-5 mt-auto row container">
            <div class="col-lg-6 col-12">

                <h4>BudgetHelper</h4>
                <p>Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                    dedicated to helping individuals take control of their finances and make informed decisions about
                    their
                    money. With our
                    user-friendly budgeting application, you can easily track your income and expenses, set budgets for
                    different
                    categories, and gain valuable insights into your spending habits.</p>
            </div>
            <div class="col-lg-6 col-12 pl-lg-5">
                <h4>Quick links</h4>
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'signup' %}">Sign Up</a>
                <a href="#">About</a>
                <a href="#">Contacts</a>
            </div>

        </div>
        <div class="social-media text-center">
            <a href="https://facebook.com"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com"><i class="fab fa-twitter"></i></a>
            <a href="https://instagram.com"><i class="fab fa-instagram"></i></a>
            <a href="https://linkedin.com"><i class="fab fa-linkedin-in"></i></a>
        </div>
        <div class="footer-copyright text-center col-12">© 2020 Copyright:
            <a href="/"> BudgetHelper</a>
        </div>
    </footer>
</body>

</html>

category/templates/category_add.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="cat-container col-sm-6 col-12" style="color:aliceblue;">
        <form action="{% url 'cat_add' %}" method="post">
            {% csrf_token %}
            <div class="row">
                {% for fields in form %}

                <div class="col-lg-5" style="margin: 5px auto;">
                    {{ fields.label }}
                </div>
                <div class="col-12 col-lg-7" style="margin: 5px auto;">
                    {{ fields }}
                </div>

                {% endfor %}
                <input type="submit" class="ml-3 btn btn-primary" value="confirm">
            </div>
        </form>
        <span style="color: rgb(206, 45, 45);">
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger" style="margin-top: 50px;">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        </span>
    </div>
</div>
{% endblock content %}

category/templates/category_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container p-5 text-white"
    style="text-align: left;margin-top: 5%;font-size: larger;background-color: rgb(83, 83, 83);border-radius: 10px;">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete?</p>
        <input type="submit" value="confirm" class="btn btn-danger">
    </form>
</div>
{% endblock content %}

category/templates/category_detail.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block title %}
Category Analytics - Budget Helper App
{% endblock title %}

{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js">
</script>
{% if category.category_info_set.all %}
<div class="row m-0">
    <canvas id="myChart" class="col-sm-6 mt-5" style="background-color: rgb(0, 18, 51); border-radius: 20px;"></canvas>
    <canvas id="pie" class="col-sm-6 mt-5"></canvas>
</div>

<script>
    var xValues = []
    var yValues = []
    var color = "white"
    // {% for obj in category.category_info_set.all %}
    xValues.push("{{ obj.date|date:'d M' }}")
    yValues.push({{ obj.spend }})
    // {% endfor %}


    console.log(xValues)
    console.log(yValues)

    new Chart("myChart", {
        type: "line",
        data: {
            labels: xValues,
            datasets: [{
                label: "Spend per day",
                lineTension: 0,
                display: true,
                fill: false,
                backgroundColor: color,
                borderColor: "rgba(254,254,254,0.7)",
                data: yValues
            }]
        },
        options: {
            legend: {
                labels: {
                    fontColor: color,
                    fontSize: 14,
                }
            },
            scales: {
                yAxes: [{
                    gridLines: {
                        color: color
                    },
                    ticks: {
                        fontColor: color,
                        fontSize: 14,
                        beginAtZero: true
                    },
                    scaleLabel: {
                        display: true,
                        fontColor: color,
                        fontSize: 14,
                        labelString: 'Amount Spend (Rs)'
                    }
                }],
                xAxes: [{
                    gridLines: {
                        color: color
                    },
                    ticks: {
                        fontColor: color,
                        fontSize: 14,
                        beginAtZero: true
                    },
                    scaleLabel: {
                        display: true,
                        labelString: 'Day',
                        fontColor: color,
                        fontSize: 14,
                    }
                }],
            },
        }
    });

    // pie chart
    var barColors = ["#060363", "#27b7de"]
    xValues = ["Amount Left", "Amount Spent"]
    yValues = ["{{ category.amt_left }}", {{ category.budget }}-{{ category.amt_left }}]
    new Chart("pie", {
        type: "pie",
        data: {
            labels: xValues,
            datasets: [{
                backgroundColor: barColors,
                data: yValues
            }]
        },
        options: {
            legend: {
                labels: {
                    fontColor: "white",
                    fontSize: 14,
                }
            },
            title: {
                display: true,
                text: "{{category.name }} Analysis",
                fontColor: "white",
                fontSize: 14,
            }
        }
    });


</script>

<div class="container mt-5 mr-auto ml-0  text-left">
    {% for i in category.category_info_set.all %}
    <div class="cat-list justify-content-between d-flex col-12">
        <span class="ml-0 ml-sm-5" style="font-weight: bold;">{{i.item}}</span>
        <span style="font-weight: bold;">{{i.spend}}</span>
        <span style="font-weight: bold;">{{i.date|date:"d D M"}}</span>
        <a href="{% url 'cat_info_delete' i.pk%}" class="btn btn-danger mr-sm-5 mr-0">Delete</a>
    </div>
    {% endfor %}
</div>
{% else %}
<a href="{% url 'cat_info_add' %}" style="color: rgb(129, 129, 129);font-size: larger;">
    <div id="add-container" class="col-sm-6 col-12">
        <b>+ Add Spending</b>
    </div>
</a>
{% endif %}
{% endblock content %}

category/templates/category_info_add_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="cat-container col-12 col-lg-6 col-sm-10" style="color:aliceblue;">
        <form action="{% url 'cat_info_add' %}" method="post">
            {% csrf_token %}
            <div class="row">
                {% for fields in form %}

                <div class="col-3" style="margin: 5px auto;">
                    {{ fields.label }}
                </div>
                <div class="col-7" style="margin: 5px auto;">
                    {{ fields }}
                </div>

                {% endfor %}
                <input type="submit" class="offset-md-1 btn btn-primary" value="confirm">
            </div>
        </form>
        <span style="color: rgb(206, 45, 45);">
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger" style="margin-top: 50px;">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        </span>
    </div>
</div>
{% endblock content %}

category/templates/category_info_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Spending History - Budget Helper App
{% endblock title %}

{% block meta %}
<meta name="description"
    content="Track and manage your spending history with Budget Helper App. View your total budget, left budget, and spent budget. Add and delete expenses by category.">
{% endblock meta %}


{% block additional %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock additional %}


{% block content %}
<div>

    <div class="spend-head">
        <div class="row">
            <div class="col-sm-4">
                <h3>&#8377 {{ budget|floatformat:2 }}</h3>
                <p>Total budget</p>
            </div>
            {% if amt_left < 0 %} <div class="col-sm-4 text-danger">
                <h3>&#8377 {{ amt_left|floatformat:2 }}</h3>
                <p>Left budget</p>
        </div>
        {% else %}
        <div class="col-sm-4 text-success">
            <h3>&#8377 {{ amt_left|floatformat:2 }}</h3>
            <p>Left budget</p>
        </div>
        {%endif%}
        <div class="col-sm-4">
            <h3>&#8377 {{ spend|floatformat:2 }}</h3>
            <p>Spent budget</p>
        </div>
    </div>
</div>

{%if category_info_list%}
<div id="btn-a" style="text-align: right;" class="offset-12">
    <a href="#" class="btn btn-primary" onclick="cat_info_add()">+ Add</a>
</div>
{% else %}
<a href="#" style="color: rgb(129, 129, 129);font-size: larger;">
    <div id="add-container" class="col-sm-6 col-12" onclick="cat_info_add()">
        <b>+ Add Expense</b>
    </div>
</a>
{% endif %}
{% for i in category_info_list %}
<div class=" spend-card col-lg-9 col-12">
    <div class="row justify-content-between d-flex ">
        <h5 class="col-sm-3 col-6 text-sm-left">{{i.item}}</h5>
        <h5 class="col-sm-3 col-6 text-sm-left">{{i.cat}}</h5>
        <h5 class="col-sm-3 col-6 text-sm-left">{{i.date|date:"d D M Y"}}</h5>
        <h5 class="col-sm-2 col-6 text-sm-left">&#8377 {{i.spend}}</h5>
        <a href="{% url 'cat_info_delete' i.pk %}" class="col-sm-1 col-12 btn btn-danger">Delete</a>
    </div>
</div>
{% endfor %}

</div>
{% endblock content %}

category/templates/category_list.html
{% extends 'base.html' %}

{% block title %}
Expense Categories - Budget Helper App
{% endblock title %}


{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
<div class="row m-0" id="reverse">
    <div class="container mt-5 mr-auto ml-0 col-sm-6">
        {% for i in category_list %}
        <div class="cat-list justify-content-between d-flex " onclick="change({{i.pk}})">
            <span class="ml-0 ml-sm-5" style="font-weight: bold;">{{i}}</span>
            <div>
                <a href="{% url 'cat_update' i.pk %}" class="btn btn-primary ">Update</a>
                <a href="{% url 'cat_delete' i.pk%}" class="btn btn-danger mr-sm-5 mr-0">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-sm-6 mr-auto ml-0">
        <canvas id="pie1" style="width:100%;max-width:700px;" style="border: 0;"></canvas>
        <script>
            var xValues = [];
            var yValues = [];
            var barColors = [
                "#7CB9E8", "#00308F", "#72A0C1", "#002D62", "#6CB4EE", "#002D62", "#007FFF", "#89CFF0",
                "#0066b2"];

            var sum = 0;

            // {% for i in category_list  %}

            xValues.push("{{i.name}}")
            yValues.push({{ i.budget }}-{{ i.amt_left }})
            sum += {{ i.amt_left }}
            // {% endfor %}
            console.log(yValues)
            xValues.push("Amount Left")
            yValues.push(sum)

            new Chart("pie1", {
                type: "pie",
                data: {
                    labels: xValues,
                    datasets: [{
                        backgroundColor: barColors,
                        data: yValues,
                        borderWidth: 0,
                    }]
                },
                options: {
                    legend: {
                        labels: {
                            fontColor: "white",
                            fontSize: 14,
                        }
                    },
                    title: {
                        display: true,
                        text: "Category Analysis",
                        fontColor: "white",
                        fontSize: 14,
                    }
                }
            });
        </script>
    </div>

</div>

{% endblock content %}

category/templates/category_update.html
{% extends 'base.html' %}

{% block title %}
Updating Category - Budget Helper App
{% endblock title %}


{% block content %}
<div class="container">
    <div class="cat-container col-sm-6 col-12" style="color:aliceblue;">
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                {% for fields in form %}

                <div class="col-lg-5" style="margin: 5px auto;">
                    {{ fields.label }}
                </div>
                <div class="col-12 col-lg-7" style="margin: 5px auto;">
                    {{ fields }}
                </div>

                {% endfor %}
                <input type="submit" class="ml-3 btn btn-primary" value="confirm">
            </div>
        </form>
        <span style="color: rgb(206, 45, 45);">
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger" style="margin-top: 50px;">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        </span>
    </div>
</div>
{% endblock content %}

category/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
About page - Budget Helper App
{% endblock title %}

{% block meta %}
<meta name="description"
    content="Learn more about Budget Helper App - a budget application based on categorical budgeting. Take control of your finances and manage your budget effectively.">
{% endblock meta %}

{% block content %}
<h1>About Page</h1>
<div class="text-white" id="about" style="margin-right: 15px;">
    <div class="row">
        <div class="col-lg-6">

            <h2>Introduction</h2>
            <p>
                Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                dedicated
                to
                helping
                individuals take control of their finances and make informed decisions about their money. With our
                user-friendly
                budgeting application, you can easily track your income and expenses, set budgets for different
                categories,
                and gain
                valuable insights into your spending habits.
                <!-- <br>
                        <b>Sign up now and take control of your expenses with Budget Helper App.</b> -->
            </p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/home.jpg' %}" alt="Budget Helper App Image">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">

            <h2>Introduction</h2>
            <p>
                Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                dedicated
                to
                helping
                individuals take control of their finances and make informed decisions about their money. With our
                user-friendly
                budgeting application, you can easily track your income and expenses, set budgets for different
                categories,
                and gain
                valuable insights into your spending habits.
                <!-- <br>
                            <b>Sign up now and take control of your expenses with Budget Helper App.</b> -->
            </p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/home.jpg' %}" alt="Budget Helper App Image">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">

            <h2>Introduction</h2>
            <p>
                Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                dedicated
                to
                helping
                individuals take control of their finances and make informed decisions about their money. With our
                user-friendly
                budgeting application, you can easily track your income and expenses, set budgets for different
                categories,
                and gain
                valuable insights into your spending habits.
                <!-- <br>
                                <b>Sign up now and take control of your expenses with Budget Helper App.</b> -->
            </p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/home.jpg' %}" alt="Budget Helper App Image">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">

            <h2>Introduction</h2>
            <p>
                Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                dedicated
                to
                helping
                individuals take control of their finances and make informed decisions about their money. With our
                user-friendly
                budgeting application, you can easily track your income and expenses, set budgets for different
                categories,
                and gain
                valuable insights into your spending habits.
                <!-- <br>
                                <b>Sign up now and take control of your expenses with Budget Helper App.</b> -->
            </p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/home.jpg' %}" alt="Budget Helper App Image">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">

            <h2>Introduction</h2>
            <p>
                Welcome to Budget Helper App, your go-to solution for effective financial management. We are
                dedicated to helping individuals take control of their finances and make informed decisions about their
                money. With our
                user-friendly budgeting application, you can easily track your income and expenses, set budgets for
                different
                categories, and gain valuable insights into your spending habits.
                <!-- <br>
                                <b>Sign up now and take control of your expenses with Budget Helper App.</b> -->
            </p>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'img/home.jpg' %}" alt="Budget Helper App Image">
        </div>
    </div>
</div>
{% endblock content %}